[build]
  publish = "docs/build"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.12.1"
  YARN_FLAGS = "--frozen-lockfile"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
