// flow-typed signature: 1bfc5a8e33cfc3607bda34098ddf2755
// flow-typed version: <<STUB>>/args_v2.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'args'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'args' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'args/index' {
  declare module.exports: $Exports<'args'>;
}
declare module 'args/index.js' {
  declare module.exports: $Exports<'args'>;
}
