// flow-typed signature: df18c1bb7965812c784f79d129b3972a
// flow-typed version: <<STUB>>/args_v^3.0.4/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'args'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'args' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'args/lib/command' {
  declare module.exports: any;
}

declare module 'args/lib/example' {
  declare module.exports: any;
}

declare module 'args/lib/examples' {
  declare module.exports: any;
}

declare module 'args/lib/help' {
  declare module.exports: any;
}

declare module 'args/lib/index' {
  declare module.exports: any;
}

declare module 'args/lib/option' {
  declare module.exports: any;
}

declare module 'args/lib/options' {
  declare module.exports: any;
}

declare module 'args/lib/parse' {
  declare module.exports: any;
}

declare module 'args/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'args/lib/command.js' {
  declare module.exports: $Exports<'args/lib/command'>;
}
declare module 'args/lib/example.js' {
  declare module.exports: $Exports<'args/lib/example'>;
}
declare module 'args/lib/examples.js' {
  declare module.exports: $Exports<'args/lib/examples'>;
}
declare module 'args/lib/help.js' {
  declare module.exports: $Exports<'args/lib/help'>;
}
declare module 'args/lib/index.js' {
  declare module.exports: $Exports<'args/lib/index'>;
}
declare module 'args/lib/option.js' {
  declare module.exports: $Exports<'args/lib/option'>;
}
declare module 'args/lib/options.js' {
  declare module.exports: $Exports<'args/lib/options'>;
}
declare module 'args/lib/parse.js' {
  declare module.exports: $Exports<'args/lib/parse'>;
}
declare module 'args/lib/utils.js' {
  declare module.exports: $Exports<'args/lib/utils'>;
}
