// flow-typed signature: 9abce63f1037943e8d24adb6d578c21b
// flow-typed version: <<STUB>>/assign-deep_v^0.4.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'assign-deep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'assign-deep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'assign-deep/index' {
  declare module.exports: $Exports<'assign-deep'>;
}
declare module 'assign-deep/index.js' {
  declare module.exports: $Exports<'assign-deep'>;
}
