// flow-typed signature: 4c3f51c9d27d8670b56515c46842e7d6
// flow-typed version: <<STUB>>/babel-plugin-external-helpers_v^6.8.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-external-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-external-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-external-helpers/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-external-helpers/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-external-helpers/lib/index'>;
}
