// flow-typed signature: 0e92e019ed050ebdfd0c930bea2eecd2
// flow-typed version: <<STUB>>/babel-preset-react-app_v^2.1.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-react-app/index' {
  declare module.exports: $Exports<'babel-preset-react-app'>;
}
declare module 'babel-preset-react-app/index.js' {
  declare module.exports: $Exports<'babel-preset-react-app'>;
}
