// flow-typed signature: 582e466d2444212814f2c93e6b0a25a1
// flow-typed version: <<STUB>>/cli-color_v^1.2.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-color' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cli-color/art' {
  declare module.exports: any;
}

declare module 'cli-color/bare' {
  declare module.exports: any;
}

declare module 'cli-color/beep' {
  declare module.exports: any;
}

declare module 'cli-color/columns' {
  declare module.exports: any;
}

declare module 'cli-color/erase' {
  declare module.exports: any;
}

declare module 'cli-color/examples/art' {
  declare module.exports: any;
}

declare module 'cli-color/examples/basic' {
  declare module.exports: any;
}

declare module 'cli-color/examples/erase' {
  declare module.exports: any;
}

declare module 'cli-color/examples/styles' {
  declare module.exports: any;
}

declare module 'cli-color/examples/throbber' {
  declare module.exports: any;
}

declare module 'cli-color/examples/xterm' {
  declare module.exports: any;
}

declare module 'cli-color/get-stripped-length' {
  declare module.exports: any;
}

declare module 'cli-color/lib/sgr' {
  declare module.exports: any;
}

declare module 'cli-color/lib/xterm-colors' {
  declare module.exports: any;
}

declare module 'cli-color/lib/xterm-match' {
  declare module.exports: any;
}

declare module 'cli-color/move' {
  declare module.exports: any;
}

declare module 'cli-color/reset' {
  declare module.exports: any;
}

declare module 'cli-color/slice' {
  declare module.exports: any;
}

declare module 'cli-color/strip' {
  declare module.exports: any;
}

declare module 'cli-color/test/__playground/throbber.formatted' {
  declare module.exports: any;
}

declare module 'cli-color/test/__playground/throbber' {
  declare module.exports: any;
}

declare module 'cli-color/test/art' {
  declare module.exports: any;
}

declare module 'cli-color/test/bare' {
  declare module.exports: any;
}

declare module 'cli-color/test/beep' {
  declare module.exports: any;
}

declare module 'cli-color/test/columns' {
  declare module.exports: any;
}

declare module 'cli-color/test/erase' {
  declare module.exports: any;
}

declare module 'cli-color/test/get-stripped-length' {
  declare module.exports: any;
}

declare module 'cli-color/test/index' {
  declare module.exports: any;
}

declare module 'cli-color/test/lib/sgr' {
  declare module.exports: any;
}

declare module 'cli-color/test/lib/xterm-colors' {
  declare module.exports: any;
}

declare module 'cli-color/test/lib/xterm-match' {
  declare module.exports: any;
}

declare module 'cli-color/test/move' {
  declare module.exports: any;
}

declare module 'cli-color/test/reset' {
  declare module.exports: any;
}

declare module 'cli-color/test/slice' {
  declare module.exports: any;
}

declare module 'cli-color/test/strip' {
  declare module.exports: any;
}

declare module 'cli-color/test/throbber' {
  declare module.exports: any;
}

declare module 'cli-color/test/visual' {
  declare module.exports: any;
}

declare module 'cli-color/test/window-size' {
  declare module.exports: any;
}

declare module 'cli-color/throbber' {
  declare module.exports: any;
}

declare module 'cli-color/window-size' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cli-color/art.js' {
  declare module.exports: $Exports<'cli-color/art'>;
}
declare module 'cli-color/bare.js' {
  declare module.exports: $Exports<'cli-color/bare'>;
}
declare module 'cli-color/beep.js' {
  declare module.exports: $Exports<'cli-color/beep'>;
}
declare module 'cli-color/columns.js' {
  declare module.exports: $Exports<'cli-color/columns'>;
}
declare module 'cli-color/erase.js' {
  declare module.exports: $Exports<'cli-color/erase'>;
}
declare module 'cli-color/examples/art.js' {
  declare module.exports: $Exports<'cli-color/examples/art'>;
}
declare module 'cli-color/examples/basic.js' {
  declare module.exports: $Exports<'cli-color/examples/basic'>;
}
declare module 'cli-color/examples/erase.js' {
  declare module.exports: $Exports<'cli-color/examples/erase'>;
}
declare module 'cli-color/examples/styles.js' {
  declare module.exports: $Exports<'cli-color/examples/styles'>;
}
declare module 'cli-color/examples/throbber.js' {
  declare module.exports: $Exports<'cli-color/examples/throbber'>;
}
declare module 'cli-color/examples/xterm.js' {
  declare module.exports: $Exports<'cli-color/examples/xterm'>;
}
declare module 'cli-color/get-stripped-length.js' {
  declare module.exports: $Exports<'cli-color/get-stripped-length'>;
}
declare module 'cli-color/index' {
  declare module.exports: $Exports<'cli-color'>;
}
declare module 'cli-color/index.js' {
  declare module.exports: $Exports<'cli-color'>;
}
declare module 'cli-color/lib/sgr.js' {
  declare module.exports: $Exports<'cli-color/lib/sgr'>;
}
declare module 'cli-color/lib/xterm-colors.js' {
  declare module.exports: $Exports<'cli-color/lib/xterm-colors'>;
}
declare module 'cli-color/lib/xterm-match.js' {
  declare module.exports: $Exports<'cli-color/lib/xterm-match'>;
}
declare module 'cli-color/move.js' {
  declare module.exports: $Exports<'cli-color/move'>;
}
declare module 'cli-color/reset.js' {
  declare module.exports: $Exports<'cli-color/reset'>;
}
declare module 'cli-color/slice.js' {
  declare module.exports: $Exports<'cli-color/slice'>;
}
declare module 'cli-color/strip.js' {
  declare module.exports: $Exports<'cli-color/strip'>;
}
declare module 'cli-color/test/__playground/throbber.formatted.js' {
  declare module.exports: $Exports<'cli-color/test/__playground/throbber.formatted'>;
}
declare module 'cli-color/test/__playground/throbber.js' {
  declare module.exports: $Exports<'cli-color/test/__playground/throbber'>;
}
declare module 'cli-color/test/art.js' {
  declare module.exports: $Exports<'cli-color/test/art'>;
}
declare module 'cli-color/test/bare.js' {
  declare module.exports: $Exports<'cli-color/test/bare'>;
}
declare module 'cli-color/test/beep.js' {
  declare module.exports: $Exports<'cli-color/test/beep'>;
}
declare module 'cli-color/test/columns.js' {
  declare module.exports: $Exports<'cli-color/test/columns'>;
}
declare module 'cli-color/test/erase.js' {
  declare module.exports: $Exports<'cli-color/test/erase'>;
}
declare module 'cli-color/test/get-stripped-length.js' {
  declare module.exports: $Exports<'cli-color/test/get-stripped-length'>;
}
declare module 'cli-color/test/index.js' {
  declare module.exports: $Exports<'cli-color/test/index'>;
}
declare module 'cli-color/test/lib/sgr.js' {
  declare module.exports: $Exports<'cli-color/test/lib/sgr'>;
}
declare module 'cli-color/test/lib/xterm-colors.js' {
  declare module.exports: $Exports<'cli-color/test/lib/xterm-colors'>;
}
declare module 'cli-color/test/lib/xterm-match.js' {
  declare module.exports: $Exports<'cli-color/test/lib/xterm-match'>;
}
declare module 'cli-color/test/move.js' {
  declare module.exports: $Exports<'cli-color/test/move'>;
}
declare module 'cli-color/test/reset.js' {
  declare module.exports: $Exports<'cli-color/test/reset'>;
}
declare module 'cli-color/test/slice.js' {
  declare module.exports: $Exports<'cli-color/test/slice'>;
}
declare module 'cli-color/test/strip.js' {
  declare module.exports: $Exports<'cli-color/test/strip'>;
}
declare module 'cli-color/test/throbber.js' {
  declare module.exports: $Exports<'cli-color/test/throbber'>;
}
declare module 'cli-color/test/visual.js' {
  declare module.exports: $Exports<'cli-color/test/visual'>;
}
declare module 'cli-color/test/window-size.js' {
  declare module.exports: $Exports<'cli-color/test/window-size'>;
}
declare module 'cli-color/throbber.js' {
  declare module.exports: $Exports<'cli-color/throbber'>;
}
declare module 'cli-color/window-size.js' {
  declare module.exports: $Exports<'cli-color/window-size'>;
}
