// flow-typed signature: fac8f0224a4e15bb6aefc8fd284e3b90
// flow-typed version: <<STUB>>/eslint-config-interactivethings_v^3.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-interactivethings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-interactivethings' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-interactivethings/index' {
  declare module.exports: $Exports<'eslint-config-interactivethings'>;
}
declare module 'eslint-config-interactivethings/index.js' {
  declare module.exports: $Exports<'eslint-config-interactivethings'>;
}
