// flow-typed signature: b8b9af7d83005fd40425722305b7d0ca
// flow-typed version: <<STUB>>/friendly-errors-webpack-plugin_v^1.6.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'friendly-errors-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'friendly-errors-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'friendly-errors-webpack-plugin/src/core/extractWebpackError' {
  declare module.exports: any;
}

declare module 'friendly-errors-webpack-plugin/src/core/formatErrors' {
  declare module.exports: any;
}

declare module 'friendly-errors-webpack-plugin/src/core/transformErrors' {
  declare module.exports: any;
}

declare module 'friendly-errors-webpack-plugin/src/formatters/defaultError' {
  declare module.exports: any;
}

declare module 'friendly-errors-webpack-plugin/src/formatters/eslintError' {
  declare module.exports: any;
}

declare module 'friendly-errors-webpack-plugin/src/formatters/moduleNotFound' {
  declare module.exports: any;
}

declare module 'friendly-errors-webpack-plugin/src/friendly-errors-plugin' {
  declare module.exports: any;
}

declare module 'friendly-errors-webpack-plugin/src/output' {
  declare module.exports: any;
}

declare module 'friendly-errors-webpack-plugin/src/transformers/babelSyntax' {
  declare module.exports: any;
}

declare module 'friendly-errors-webpack-plugin/src/transformers/esLintError' {
  declare module.exports: any;
}

declare module 'friendly-errors-webpack-plugin/src/transformers/moduleNotFound' {
  declare module.exports: any;
}

declare module 'friendly-errors-webpack-plugin/src/utils/colors' {
  declare module.exports: any;
}

declare module 'friendly-errors-webpack-plugin/src/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'friendly-errors-webpack-plugin/index' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin'>;
}
declare module 'friendly-errors-webpack-plugin/index.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin'>;
}
declare module 'friendly-errors-webpack-plugin/src/core/extractWebpackError.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin/src/core/extractWebpackError'>;
}
declare module 'friendly-errors-webpack-plugin/src/core/formatErrors.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin/src/core/formatErrors'>;
}
declare module 'friendly-errors-webpack-plugin/src/core/transformErrors.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin/src/core/transformErrors'>;
}
declare module 'friendly-errors-webpack-plugin/src/formatters/defaultError.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin/src/formatters/defaultError'>;
}
declare module 'friendly-errors-webpack-plugin/src/formatters/eslintError.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin/src/formatters/eslintError'>;
}
declare module 'friendly-errors-webpack-plugin/src/formatters/moduleNotFound.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin/src/formatters/moduleNotFound'>;
}
declare module 'friendly-errors-webpack-plugin/src/friendly-errors-plugin.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin/src/friendly-errors-plugin'>;
}
declare module 'friendly-errors-webpack-plugin/src/output.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin/src/output'>;
}
declare module 'friendly-errors-webpack-plugin/src/transformers/babelSyntax.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin/src/transformers/babelSyntax'>;
}
declare module 'friendly-errors-webpack-plugin/src/transformers/esLintError.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin/src/transformers/esLintError'>;
}
declare module 'friendly-errors-webpack-plugin/src/transformers/moduleNotFound.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin/src/transformers/moduleNotFound'>;
}
declare module 'friendly-errors-webpack-plugin/src/utils/colors.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin/src/utils/colors'>;
}
declare module 'friendly-errors-webpack-plugin/src/utils/index.js' {
  declare module.exports: $Exports<'friendly-errors-webpack-plugin/src/utils/index'>;
}
