// flow-typed signature: 67d91d45390cd87b4574ae04c4f9e246
// flow-typed version: <<STUB>>/github-slugger_v^1.1.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'github-slugger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'github-slugger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'github-slugger/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'github-slugger/index' {
  declare module.exports: $Exports<'github-slugger'>;
}
declare module 'github-slugger/index.js' {
  declare module.exports: $Exports<'github-slugger'>;
}
declare module 'github-slugger/test/index.js' {
  declare module.exports: $Exports<'github-slugger/test/index'>;
}
