// flow-typed signature: 8942b04cd9317aef82707aae14680920
// flow-typed version: <<STUB>>/object-values_v^1.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-values'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-values' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'object-values/index' {
  declare module.exports: $Exports<'object-values'>;
}
declare module 'object-values/index.js' {
  declare module.exports: $Exports<'object-values'>;
}
