// flow-typed signature: 1d3b50e14293f05b2478c0ea235a0189
// flow-typed version: <<STUB>>/react-dev-utils_v^0.5.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dev-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dev-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dev-utils/checkRequiredFiles' {
  declare module.exports: any;
}

declare module 'react-dev-utils/clearConsole' {
  declare module.exports: any;
}

declare module 'react-dev-utils/FileSizeReporter' {
  declare module.exports: any;
}

declare module 'react-dev-utils/formatWebpackMessages' {
  declare module.exports: any;
}

declare module 'react-dev-utils/getProcessForPort' {
  declare module.exports: any;
}

declare module 'react-dev-utils/InterpolateHtmlPlugin' {
  declare module.exports: any;
}

declare module 'react-dev-utils/openBrowser' {
  declare module.exports: any;
}

declare module 'react-dev-utils/prompt' {
  declare module.exports: any;
}

declare module 'react-dev-utils/WatchMissingNodeModulesPlugin' {
  declare module.exports: any;
}

declare module 'react-dev-utils/webpackHotDevClient' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dev-utils/checkRequiredFiles.js' {
  declare module.exports: $Exports<'react-dev-utils/checkRequiredFiles'>;
}
declare module 'react-dev-utils/clearConsole.js' {
  declare module.exports: $Exports<'react-dev-utils/clearConsole'>;
}
declare module 'react-dev-utils/FileSizeReporter.js' {
  declare module.exports: $Exports<'react-dev-utils/FileSizeReporter'>;
}
declare module 'react-dev-utils/formatWebpackMessages.js' {
  declare module.exports: $Exports<'react-dev-utils/formatWebpackMessages'>;
}
declare module 'react-dev-utils/getProcessForPort.js' {
  declare module.exports: $Exports<'react-dev-utils/getProcessForPort'>;
}
declare module 'react-dev-utils/InterpolateHtmlPlugin.js' {
  declare module.exports: $Exports<'react-dev-utils/InterpolateHtmlPlugin'>;
}
declare module 'react-dev-utils/openBrowser.js' {
  declare module.exports: $Exports<'react-dev-utils/openBrowser'>;
}
declare module 'react-dev-utils/prompt.js' {
  declare module.exports: $Exports<'react-dev-utils/prompt'>;
}
declare module 'react-dev-utils/WatchMissingNodeModulesPlugin.js' {
  declare module.exports: $Exports<'react-dev-utils/WatchMissingNodeModulesPlugin'>;
}
declare module 'react-dev-utils/webpackHotDevClient.js' {
  declare module.exports: $Exports<'react-dev-utils/webpackHotDevClient'>;
}
