// flow-typed signature: e597ed8e9a20a73e110fd44d29d5aa91
// flow-typed version: <<STUB>>/release_v^3.0.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'release'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'release' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'release/bin/release' {
  declare module.exports: any;
}

declare module 'release/lib/bump' {
  declare module.exports: any;
}

declare module 'release/lib/changelog' {
  declare module.exports: any;
}

declare module 'release/lib/choices' {
  declare module.exports: any;
}

declare module 'release/lib/commits' {
  declare module.exports: any;
}

declare module 'release/lib/connect' {
  declare module.exports: any;
}

declare module 'release/lib/definitions' {
  declare module.exports: any;
}

declare module 'release/lib/group' {
  declare module.exports: any;
}

declare module 'release/lib/hook' {
  declare module.exports: any;
}

declare module 'release/lib/pick-commit' {
  declare module.exports: any;
}

declare module 'release/lib/repo' {
  declare module.exports: any;
}

declare module 'release/lib/spinner' {
  declare module.exports: any;
}

declare module 'release/lib/tags' {
  declare module.exports: any;
}

// Filename aliases
declare module 'release/bin/release.js' {
  declare module.exports: $Exports<'release/bin/release'>;
}
declare module 'release/lib/bump.js' {
  declare module.exports: $Exports<'release/lib/bump'>;
}
declare module 'release/lib/changelog.js' {
  declare module.exports: $Exports<'release/lib/changelog'>;
}
declare module 'release/lib/choices.js' {
  declare module.exports: $Exports<'release/lib/choices'>;
}
declare module 'release/lib/commits.js' {
  declare module.exports: $Exports<'release/lib/commits'>;
}
declare module 'release/lib/connect.js' {
  declare module.exports: $Exports<'release/lib/connect'>;
}
declare module 'release/lib/definitions.js' {
  declare module.exports: $Exports<'release/lib/definitions'>;
}
declare module 'release/lib/group.js' {
  declare module.exports: $Exports<'release/lib/group'>;
}
declare module 'release/lib/hook.js' {
  declare module.exports: $Exports<'release/lib/hook'>;
}
declare module 'release/lib/pick-commit.js' {
  declare module.exports: $Exports<'release/lib/pick-commit'>;
}
declare module 'release/lib/repo.js' {
  declare module.exports: $Exports<'release/lib/repo'>;
}
declare module 'release/lib/spinner.js' {
  declare module.exports: $Exports<'release/lib/spinner'>;
}
declare module 'release/lib/tags.js' {
  declare module.exports: $Exports<'release/lib/tags'>;
}
