// flow-typed signature: 4ca99a57ca0d2825dc557529183e9cb7
// flow-typed version: <<STUB>>/sander_v^0.6.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sander'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sander' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sander/dist/sander.cjs' {
  declare module.exports: any;
}

declare module 'sander/dist/sander.es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sander/dist/sander.cjs.js' {
  declare module.exports: $Exports<'sander/dist/sander.cjs'>;
}
declare module 'sander/dist/sander.es.js' {
  declare module.exports: $Exports<'sander/dist/sander.es'>;
}
