// flow-typed signature: e92a4a1512cfea4bd86edb9a9f63a3ed
// flow-typed version: <<STUB>>/srcset_v^1.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'srcset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'srcset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'srcset/index' {
  declare module.exports: $Exports<'srcset'>;
}
declare module 'srcset/index.js' {
  declare module.exports: $Exports<'srcset'>;
}
