// flow-typed signature: 2d66c0a59049567570cc863c39418217
// flow-typed version: <<STUB>>/unfetch_v^2.1.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unfetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unfetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unfetch/dist/unfetch.es' {
  declare module.exports: any;
}

declare module 'unfetch/dist/unfetch' {
  declare module.exports: any;
}

declare module 'unfetch/dist/unfetch.umd' {
  declare module.exports: any;
}

declare module 'unfetch/polyfill' {
  declare module.exports: any;
}

declare module 'unfetch/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unfetch/dist/unfetch.es.js' {
  declare module.exports: $Exports<'unfetch/dist/unfetch.es'>;
}
declare module 'unfetch/dist/unfetch.js' {
  declare module.exports: $Exports<'unfetch/dist/unfetch'>;
}
declare module 'unfetch/dist/unfetch.umd.js' {
  declare module.exports: $Exports<'unfetch/dist/unfetch.umd'>;
}
declare module 'unfetch/polyfill.js' {
  declare module.exports: $Exports<'unfetch/polyfill'>;
}
declare module 'unfetch/src/index.js' {
  declare module.exports: $Exports<'unfetch/src/index'>;
}
