// flow-typed signature: 954fa07f9602f5837965cfcf35ecb95b
// flow-typed version: <<STUB>>/react-router-scroll_v^0.4.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-scroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-scroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-scroll/lib/index' {
  declare module.exports: any;
}

declare module 'react-router-scroll/lib/ScrollBehaviorContext' {
  declare module.exports: any;
}

declare module 'react-router-scroll/lib/ScrollContainer' {
  declare module.exports: any;
}

declare module 'react-router-scroll/lib/StateStorage' {
  declare module.exports: any;
}

declare module 'react-router-scroll/lib/useScroll' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-scroll/lib/index.js' {
  declare module.exports: $Exports<'react-router-scroll/lib/index'>;
}
declare module 'react-router-scroll/lib/ScrollBehaviorContext.js' {
  declare module.exports: $Exports<'react-router-scroll/lib/ScrollBehaviorContext'>;
}
declare module 'react-router-scroll/lib/ScrollContainer.js' {
  declare module.exports: $Exports<'react-router-scroll/lib/ScrollContainer'>;
}
declare module 'react-router-scroll/lib/StateStorage.js' {
  declare module.exports: $Exports<'react-router-scroll/lib/StateStorage'>;
}
declare module 'react-router-scroll/lib/useScroll.js' {
  declare module.exports: $Exports<'react-router-scroll/lib/useScroll'>;
}
