// flow-typed signature: b38ba2b03620ca5ae212e5c75282c859
// flow-typed version: <<STUB>>/strip-indent_v^2.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strip-indent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'strip-indent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'strip-indent/index' {
  declare module.exports: $Exports<'strip-indent'>;
}
declare module 'strip-indent/index.js' {
  declare module.exports: $Exports<'strip-indent'>;
}
