import React from 'react';
import {transform} from 'buble';
import requireModuleDefault from './requireModuleDefault';

let cached = {};
const cachedTransform = (jsx) => {
  if (cached[jsx]) {
    return cached[jsx];
  }
  const transformed = transform(jsx).code;
  cached[jsx] = transformed;
  return transformed;
};

export default (jsx, imports) => {
  try {
    const importKeys = Object.keys(imports).filter((k) => imports[k]);
    const importModules = importKeys.map((k) => requireModuleDefault(imports[k]));
    const transformed = cachedTransform(jsx);
    // Heuristic: return the _first_ top-level call to React.createElement.
    // In the code generated by Babel, we can assume this is either after a newline or at the beginning of the code
    const code = transformed.replace(/(^|\n)React\.createElement/, ';return React.createElement');
    const element = (new Function('React', ...importKeys, code))(React, ...importModules); // eslint-disable-line no-new-func
    return {code, element};
  } catch (error) {
    return {error};
  }
};
